
PROJECT_NAME=${PROJECT_NAME:?"Need to set PROJECT_NAME"}
IMAGE_NAME=${IMAGE_NAME:?"Need to set IMAGE_NAME"}
IMAGE_VERSION=${IMAGE_VERSION:?"Need to set IMAGE_VERSION"}
RANCHER_SERVER_URL=${RANCHER_SERVER_URL:?"Need to set RANCHER_SERVER_URL"}
RANCHER_ACCESS_KEY=${RANCHER_ACCESS_KEY:?"Need to set RANCHER_ACCESS_KEY"}
RANCHER_SECRET_KEY=${RANCHER_SECRET_KEY:?"Need to set RANCHER_SECRET_KEY"}

rancher-compose -p $PROJECT_NAME --url $RANCHER_SERVER_URL --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --debug up -u -c -p -d  || exit $?
